apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer-chart.fullname" . }}
  labels:
    {{- include "producer-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: exporter
  selector:
    {{- include "producer-chart.selectorLabels" . | nindent 4 }}
